name: Create Linode Linux VM

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2

      - name: Run bash script
        shell: bash
        run: |
          chmod +x ./linode/linode.sh
          ./linode/linode.sh $TOKEN $PASS
        env:
          TOKEN:  '${{ TOKEN }}'
          PASS:   '${{ PASS }}'