name: Linode

on: push

env:
  TOKEN:  ${{ secrets.TOKEN }}
  PASS:   ${{ secrets.PASS }}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2

      - name: Run bash script
        shell: bash
        run: |
          pwd
          chmod +x "${GITHUB_WORKSPACE}/.github/Linode/linode.sh"
          "${GITHUB_WORKSPACE}/.github/Linode/Linode.sh $TOKEN $PASS"